//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string BRAKE = "brake";
        
        public const string ACCEL = "accel";
        
        public const string TURN_LEFT = "turn_left";
        
        public const string TURN_RIGHT = "turn_right";
        
        public const string DRIFT = "drift";
        
        public const string SHIFT_UP = "shift_up";
        
        public const string SHIFT_DOWN = "shift_down";
    }
}
